[package]
name = "mania_game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
rodio = "0.17"
rfd = "0.12"
zip = "0.6"
discord-rich-presence = "0.2.5"
[profile.release]
# Avoid opening console
panic = 'abort'

[package.metadata.macroquad]
windows_subsystem = "windows"
